version: '3.8'

services:
  main-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - simple-file-storage
    volumes:
      - '.env:/.env'
    ports:
      - 8080:8080

  nginx:
    restart: unless-stopped
    image: 'registry.docker.ir/library/nginx:1.23.4'
    ports:
        - 8085:80
    volumes:
        - './devops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    networks: 
        - simple-file-storage
networks:
  simple-file-storage:
    driver: bridge
    name: simple-file-storage
